
services:
  db: 
    image: postgres:16 
    ports:
      - "5432:5432" 
    container_name: rekomind_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/ 
    networks:
      - quiznet 
    restart: unless-stopped

  backend: 
    container_name: rekomind 
    build: . 
    ports:
      - "8000:8000" 
    environment:
      DATABASE_URL: ${DATABASE_URL} 
      SECRET_KEY: ${SECRET_KEY}
      PORT: 8000 
    volumes:
      - .:/app 
    depends_on:
      - db 
    networks:
      - quiznet 
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload 

  #  --- Ngrok Setup ---
  # ngrok:
  #   image: ngrok/ngrok:latest 
  #   container_name: rekomind_ngrok 
  #   restart: unless-stopped
  #   depends_on:
  #     - backend 
  #   environment:
  #     NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
  #   command: http backend:8000
  #   networks:
  #     - quiznet
  

# --- Cloudflare tunnel setup ---
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: rekomindTunnel
    restart: unless-stopped
    depends_on:
      - backend
    command: tunnel --no-autoupdate run --token ${CF_TUNNEL_TOKEN}
    environment:
      TUNNEL_TOKEN: ${CF_TUNNEL_TOKEN}
    networks:
      - quiznet

networks:
  quiznet: 
    driver: bridge

volumes:
  postgres_data: 