"""Add new profile fields to user table

Revision ID: 01fd00e482fb
Revises: f6710a9d78dc
Create Date: 2025-05-12 10:42:21.238086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01fd00e482fb'
down_revision: Union[str, None] = 'f6710a9d78dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=150), nullable=True))
    op.add_column('user', sa.Column('education_level', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('institution_name', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('favorite_subjects', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'favorite_subjects')
    op.drop_column('user', 'institution_name')
    op.drop_column('user', 'education_level')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
