"""Add UserAnswerDetail table and relation

Revision ID: 1a1f038833d9
Revises: 89bc39bf28bc
Create Date: 2025-06-12 09:55:07.862946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from fastapi_users_db_sqlalchemy.generics import GUID


# revision identifiers, used by Alembic.
revision: str = '1a1f038833d9'
down_revision: Union[str, None] = '89bc39bf28bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_answer_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quiz_attempt_id', sa.UUID(), nullable=False),
    # sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options_presented', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_answer', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('category_name', sa.String(length=255), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['quiz_attempt_id'], ['quiz_attempt.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_answer_detail_quiz_attempt_id'), 'user_answer_detail', ['quiz_attempt_id'], unique=False)
    op.create_index(op.f('ix_user_answer_detail_user_id'), 'user_answer_detail', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_answer_detail_user_id'), table_name='user_answer_detail')
    op.drop_index(op.f('ix_user_answer_detail_quiz_attempt_id'), table_name='user_answer_detail')
    op.drop_table('user_answer_detail')
    # ### end Alembic commands ###
